name: Build and deploy Python app to Azure Web App - Star-Segmentor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          wget https://github.com/Puneet-Bajaj-IITM/image-segmentation/releases/download/v1.0.0/star-segmentor.zip
          unzip -o star-segmentor.zip -d ${{ github.workspace }}

      - name: Zip artifact for deployment
        run: zip -r release.zip star-segmentor/*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip -o release.zip -d ${{ github.workspace }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Star-Segmentor'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6A4D988E5AEA4B01BFC476E6E84677AF }}

  run-app:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Execute
        run: python ${{ github.workspace }}/star-segmentor/app.py
